### PR TITLE
First Deployment to PyPi

### PR DESCRIPTION
**Pull request by aaron-wilson-bfg**
https://pypi.org/project/GameBenchAPI-PyClient-BigFish/#description

Can someone try installing from pip? `pip install GameBenchAPI-PyClient-BigFish`

### CODE REVIEW

**Comment by aaron-wilson-bfg** [comment]
Once this is approved and merged, I'll get a release tagged.

**Comment by kawika-brennan-bfg** [comment]
I am able to install the package with a pip command, also here is the output of pip show:
`pip show GameBenchAPI-PyClient-BigFish
Name: GameBenchAPI-PyClient-BigFish
Version: 0.1.1
Summary: A GameBench API Library Client.
Home-page: https://github.com/bigfishgames/GameBenchAPI-PyClient
Author: Big Fish Games, Inc.
Author-email: 
License: UNKNOWN
Location: /Users/kawika.../lib/python3.7/site-packages
Requires: coverage, pandas, requests-mock, urllib3
Required-by: 
`
I am concerned that 'Author-email', 'License', and 'Required-by' should be populating differently.

**Comment by aaron-wilson-bfg** [comment]
> I am able to install the package with a pip command, also here is the output of pip show:
> 
> > pip show GameBenchAPI-PyClient-BigFish
> > Name: GameBenchAPI-PyClient-BigFish
> > Version: 0.1.1
> > Summary: A GameBench API Library Client.
> > Home-page: https://github.com/bigfishgames/GameBenchAPI-PyClient
> > Author: Big Fish Games, Inc.
> > Author-email:
> > License: UNKNOWN
> > Location: /Users/kawika.../lib/python3.7/site-packages
> > Requires: coverage, pandas, requests-mock, urllib3
> > Required-by:
> 
> I am concerned that 'Author-email', 'License', and 'Required-by' should be populating differently.

I can put in a link to our Gitter for the author-email. Required-by should be empty until something public requires it. I don't know why the License is unknown. The PyPi site has it. Maybe I need to add an entry in setup.py besides the classifier?

**Comment by kawika-brennan-bfg** [comment]
> > I am able to install the package with a pip command, also here is the output of pip show:
> > > pip show GameBenchAPI-PyClient-BigFish
> > > Name: GameBenchAPI-PyClient-BigFish
> > > Version: 0.1.1
> > > Summary: A GameBench API Library Client.
> > > Home-page: https://github.com/bigfishgames/GameBenchAPI-PyClient
> > > Author: Big Fish Games, Inc.
> > > Author-email:
> > > License: UNKNOWN
> > > Location: /Users/kawika.../lib/python3.7/site-packages
> > > Requires: coverage, pandas, requests-mock, urllib3
> > > Required-by:
> > 
> > 
> > I am concerned that 'Author-email', 'License', and 'Required-by' should be populating differently.
> 
> I can put in a link to our Gitter for the author-email. Required-by should be empty until something public requires it. I don't know why the License is unknown. The PyPi site has it. Maybe I need to add an entry in setup.py besides the classifier?

Unsure about the license. While searching the net about classifiers, I noticed there could be a license field added to the setup file https://docs.python.org/3/distutils/setupscript.html#additional-meta-data
Maybe that is the correct route? I am unsure how to test that at the moment.

**Comment by joseph-losee-bfg** [comment]
"Requires: coverage, ... requests-mock,"
Correct me if I'm wrong, but shouldn't coverage & requests mock be dev-only requirements and not be present in the package?

**Comment by kawika-brennan-bfg** [comment]
Submitted #37 as part of testing this pull request.

**Comment by aaron-wilson-bfg** [comment]
> "Requires: coverage, ... requests-mock,"
> Correct me if I'm wrong, but shouldn't coverage & requests mock be dev-only requirements and not be present in the package?

You are correct! I will be pushing a fix for this particular issue soon.

**Comment by aaron-wilson-bfg** [comment]
@joseph-losee-bfg 
I think I've made the changes you requested. Please review so we can merge this one in.

**Pull request merged**
